name: trible
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  flutter_slidable: ^4.0.0
  flutter_slider_drawer: ^3.0.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  hooks_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  collection: ^1.19.1
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/trible-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/trible-logo.png"
    background_color: "#F5FAFC"
    theme_color: "#F5FAFC"
  windows:
    generate: true
    image_path: "assets/images/trible-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/trible-logo.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
